# Schema for the configuration files of the DnD Initiative module.
dnd_initiative.settings:
  type: config_object
  label: 'DnD Initiative settings'
  mapping:
    example:
      type: string
      label: 'Example'
