<?php

/**
 * @file
 * Primary module hooks for DnD Initiative module.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function dnd_initiative_theme() {
  return [
    'dnd_entity' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for dnd entity templates.
 *
 * Default template: dnd-entity.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the dnd entity information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_dnd_entity(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

